upload_max_filesize = 100M
post_max_size = 108M
short_open_tag = On
opcache.revalidate_freq = 0
display_errors = On
date.timezone = Europe/Moscow
session.cookie_httponly = On
max_input_vars = 10000
memory_limit = 512M
session.save_path = /tmp/
realpath_cache_size = 4096K
realpath_cache_ttl = 600

# Для Codeception при команде: php vendor/bin/codecept bootstrap
register_argc_argv = On
